[mypy]
python_version = 3.10

# Strictness
disallow_untyped_defs = True
check_untyped_defs = True
warn_return_any = True
warn_unused_configs = True
warn_no_return = True
warn_redundant_casts = True

# Stubs
ignore_missing_imports = False
install_types = False
